spring.application.name=backend

# Configuração de Conexão com o Banco de Dados (PostgreSQL)
# Se estiver na Render, ele lê a variável JDBC_DATABASE_URL. Se estiver no seu PC, usa o localhost!
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/librastalk}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:admin}

# Configurações do JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true